config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "comics#index"

  resources :comics, except: [:index] do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:update, :destroy]

  get "profile", to: "pages#profile"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :comic

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user

  validates :genre, presence: true
  validates :title, presence: true
  validates :author, presence: true

  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comics
  has_many :bookings

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @comic = Comic.find(params[:comic_id])
    @booking.comic = @comic
    @booking.status = "Pending"
    if @booking.save!
      #redirect_to booking_path(@booking)
      redirect_to profile_path()

    else
      redirect_to comic_path(@comic)
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(status:params[:status])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path, status: :see_other
  end

  private

  def set_comic
    @comic = Comic.find(params[:comic_id])
  end

  def booking_params
    params[:booking].permit(:start_date, :end_date, :status)
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  # skip_before_action
  before_action :set_comic, only: %i[ show edit update destroy ]

  def index
    @comics = Comic.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR author ILIKE :query"
      @comics = @comics.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @comic = Comic.new
  end

  def edit
  end

  def create
    @comic = Comic.new(comic_params)
    @comic.user = current_user
    if @comic.save
      redirect_to @comic, notice: "Comic was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @comic.update(comic_params)
      redirect_to @comic, notice: "Comic was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comic.destroy!
    redirect_to comics_url, notice: "Comic was successfully destroyed.", status: :see_other
  end

  private
  def set_comic
    @comic = Comic.find(params[:id])
  end

  def comic_params
    params.require(:comic).permit(:title, :author, :genre, :user_id, :poster)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    @mybookings = Booking.where(user: current_user)
    @mycomics = Comic.where(user: current_user)
    @pending_bookings = Booking.where(comic_id: @mycomics.pluck(:id), status: "Pending")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="confirmation-box col-md-4">
  <div class="listing-price">
    <div class="form-group">
      <h4>$<%= @comic.price %></h4>

      <%= simple_form_for [@comic, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>

        <%= f.submit "Request to book", class: "btn btn-danger form-control" %>
        <br><br>
        <p class="text-center" style="color: grey">You won't be charged yet</p>
        <p class="text-center" style="color: grey">-- Or --</p>

        <button class="btn btn-primary custom-link form-control"><%= link_to "Contact owner", conversations_path %></button>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container bg-light p-4">
  <h1 class="my-4">Your Bookings</h1>
  <ul class="list-group">
    <% @bookings.each do |booking| %>
      <li class="list-group-item">
        <%= booking.comic.title %> - <%= booking.start_date %> to <%= booking.end_date %>
      </li>
    <% end %>
  </ul>
</div>

app/views/bookings/new.html.erb
<%= render "bookings/booking_form" %>

app/views/bookings/show.html.erb
<div class="container-listing">
  <br>
  <h2><strong>Congratulations, your booking has been confirmed!</strong></h2><br>
  <h3><strong>Your comics details</strong></h3><br>

  <strong>Start Date: <%= @booking.start_date %></strong> | <strong>End Date: <%= @booking.end_date %></strong>

  <h4><strong><%= @booking.comic.title %></strong></h4>
  <h4><strong><%= @booking.comic.genre %></strong></h4>
  <h4><strong><%= @booking.comic.author %></strong></h4>
  <p>Location of your comic: <%= @booking.comic.address %></p>
  <p><%= @booking.comic.description %></p>

  <div class="booking-image"><br>
    <img src=<%= @booking.comic.poster %> alt="Your Comic Cov'" width="1000" class="img-responsive">
  </div>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/comics/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="bg-white rounded p-3 shadow">
        <h1 class="text-center mb-4">Which comic would you like to propose?</h1> <!-- Ajout du titre h1 -->
        <%= form_with(model: @comic, url: comics_path, method: :post) do |form| %>
          <div class="mb-3">
            <%= form.label :title, class: "form-label" %>
            <%= form.text_field :title, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :author, class: "form-label" %>
            <%= form.text_field :author, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :genre, class: "form-label" %>
            <%= form.text_field :genre, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :poster, class: "form-label" %>
            <%= form.text_field :poster, class: "form-control" %>
          </div>
          <div class="mb-3 text-center">
            <%= form.submit "Submit", class: "btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comics/create.html.erb
<h1>Comics#create</h1>
<p>Find me in app/views/comics/create.html.erb</p>

app/views/comics/destroy.html.erb
<h1>Comics#destroy</h1>
<p>Find me in app/views/comics/destroy.html.erb</p>

app/views/comics/edit.html.erb
<h1>Comics#edit</h1>
<p>Find me in app/views/comics/edit.html.erb</p>

app/views/comics/index.html.erb
<div class="container">
  <div class="row justify-content-center">
  <% @comics.each do |comic| %>
    <div class="col-md-4 col-sm-8 col-lg-4">
      <div class="card mb-4 custom-card">
        <div class="card-body d-flex justify-content-between align-items-center">
          <div>
            <h5 class="card-title"><%= comic.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted">by <%= comic.author %></h6>
            <p class="card-text"><strong>Genre:</strong> <%= comic.genre %></p>
            <p class="card-text"><strong>User:</strong> <%= comic.user.email %></p>
          </div>
          <% if comic.poster %>
          <div>
            <%= image_tag comic.poster, class: "img-fluid poster-image" %>
          </div>
          <% else  %>
           <div>
            <img src="https://img.freepik.com/free-vector/colorful-comic-magazine-cover-template_225004-799.jpg" class="img-fluid poster-image">
          </div>
          <% end %>
        </div>
          <div>
          <%= link_to "View", comic, class: "btn btn-info" %>
          </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/comics/new.html.erb
<%= render "comics/form" %>

app/views/comics/show.html.erb
<div class="container vh-100 d-flex justify-content-center align-items-center">
  <div class="col-md-6">
    <div class="card p-4 shadow">
      <h5 class="card-title text-center mb-4">Comic Details</h5>
      <div class="card-body">
        <h3 class="tlt text-center"><%= @comic.title %></h3>
        <p class="ids"><strong>Author:</strong> <%= @comic.author %></p>
        <p class="ids"><strong>Genre:</strong> <%= @comic.genre %></p>
        <p class="ids"><strong>Published in:</strong> <%= @comic.published_in %></p>
        <hr>
        <h4 class="text-center">Book the Comic</h4>
        <div style="display: flex;justify-content: center;">
        <%= simple_form_for([@comic, @booking]) do |f| %>
          <div class="mb-3 text-center"> <!-- Centrer les champs -->
            <%= f.input :start_date, html5: true, input_html: { class: "form-control", placeholder: "Start Date" } %>
          </div>
          <div class="mb-3 text-center"> <!-- Centrer les champs -->
            <%= f.input :end_date, html5: true, input_html: { class: "form-control", placeholder: "End Date" } %>
          </div>
          <div class="text-center">
            <%= f.button :submit, "Book Comic", class: "btn btn-secondary" %> <!-- Bouton en gris -->
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comics/update.html.erb
<h1>Comics#update</h1>
<p>Find me in app/views/comics/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comixbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'custom', "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="footer">
    <div class="footer-inner">
        <div class="footer-columns">
            <div class="footer-column">
                <h3 class="spefont">Explorer</h3>
                <ul>
                    <li><a href="#">Welcome</a></li>
                    <li><a href="#">Search for comix</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3 class="spefont">About us</h3>
                <ul>
                    <li><a href="#">Who are we ?</a></li>
                    <li><a href="#">Our team</a></li>
                    <li><a href="#">Contact us</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3 class="spefont">Assistance</h3>
                <ul>
                    <li><a href="#">General condtions</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-info">
            <p>&copy; Comixbnb</p>
            <div class="social-links">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </div>
</footer>

app/views/pages/profile.html.erb
<div class="container">
<h1>Profile</h1>

  <%= link_to "Add Comic Book", new_comic_path, id: "add-comic-button", class: "btn btn-primary" %>
</div>

<div id="add-comic-form" style="display: none;">
  <%= render 'comics/form' %>

</div>

  <h2>Email: <%= current_user.email %></h2>

  <%= button_to "Reset Password", "#", method: :post, class: "dropdown-item", remote: true %>

  <h2>First Name: <%=current_user.first_name%></h2>

  <h2>Last Name: <%=current_user.last_name %></h2>

  <h2>Address: <%=current_user.address%></h2>

<h2>Bookings Waiting for Approval:</h2>
  <% @pending_bookings.each do |booking| %>
    <p><%= booking.status %></p>
      <%= button_to "Accept", booking_path(booking, status: 'Accepted'), method: :patch, data: { confirm: "Are you sure you want to accept thisbooking?" } %>
      <%= button_to "Reject", booking_path(booking, status: 'Rejected'), method: :patch, data: { confirm: "Are you sure you want to reject thi booking?" } %>
  <% end %>

  <h2>Bookings Processed:</h2>
  <% @mybookings.each do |booking| %>
    <p><%= booking.status %></p>
  <% end %>
  <div id="reset-password-message" style="display: none;">
  <div class="text-end">
  A reset password link has been sent to your e-mail address.
</div>
</div class="container">

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="toggling" data-controller="toggle">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dlmpwvjpw/image/upload/v1709035117/ComixBnB/comixbnb_logo.png", style: "width: 125px; height: auto" %>
      <% end %>

      <div  class="btn-group rounded-lg mt-6" role="group" aria-label="Basic browsing toggle button group">
        <input type="genre" class="btn-check rounded-lg" name="btnheader" id="btngenre" autocomplete="off" checked>
        <label data-action="click->toggle#fire" class="btn btn-outline-secondary" for="btngenre">Search a comic</label>
      </div>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://res.cloudinary.com/dlmpwvjpw/image/upload/v1709207349/Firefly_-Design_a_logo_for_the_Comix_Trip_app_merging_pixel_art_and_hand-drawn_illustration_featu_3_lpuhud.jpg", class: "avatar", alt: "dropdown menu" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", profile_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fa-solid fa-power-off fa-2x p-3"></i>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3 d-none" data-toggle-target="togglableElement">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"%>
        <%= submit_tag "Search", name: "", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
 </div>
</div>